IMAGO_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <account>
      user: <user>
      password: <password>
      role: <role>  
      database: IMAGO
      warehouse: IMAGO_MIGRATION
      schema: dbo
      threads: 4
      client_session_keep_alive: False 